### PR TITLE
fix(merge): omit agency_id field from routes in mtc merges

### LINKED ISSUE #233: agency_id should not be added to routes table in MTC merges
## Observed behavior (please include a screenshot if possible)

During feed merges, the _agency_id_ field is added to the _routes_ table even when it's not necessary. This breaks MTC's workflow.

## Expected behavior

During MTC feed merges, the _agency_id_ field should never be added to the _routes_ table.

## Steps to reproduce the problem

Attempt to merge 2 fields.

## Any special notes on configuration used

MTC extension is enabled in server.yml file.

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

https://github.com/ibi-group/datatools-server/commit/cf73a2f2e017a09720059bd2b5af095f479c69da

https://github.com/conveyal/datatools-ui/commit/4af00b7c61eb66731c22f1b3d7bbc8c30d5da695

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

From the email forwarded to me, it seems that MTC wants to never have the _agency_id_ field included in the _routes.txt_ file. So I made some code that does just that. 

Fixes #233.

### CODE REVIEW

**Comment by landonreed** [comment]
Waiting for confirmation from MTC that `agency_id` should *never* be included in an exported feed. I somewhat doubt that this was their intent.

**Comment by evansiroky** [comment]
The latest refactor should address all of these use cases.

**Comment by landonreed** [comment]
Sorry to go back and forth on this. I think a more general way to handle this might be to "peek" at each file to be merged and get the common fields shared between them. Then, instead of iterating over all of the specFields, we could iterate over the sharedFields and safely write out all of these fields. I tried this out here: #235

**Comment by evansiroky** [comment]
While #235 seems like a reasonable thing to do, I don't believe #235 would account for scenario 3:

> Scenario 3: agency_id field is included in routes.txt file of both active and future feeds, but without values. Merged feed should eliminate the field.

**Comment by landonreed** [comment]
Ah, you're right. Checking to see if they can live without that case.

**Comment by landonreed** [comment]
Closing in favor of fixes contained in #235.

**Pull request closed without merging**
