### PR TITLE
MobilityData Validator v6

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
Upgrade!

### CODE REVIEW

**Review by br648 — APPROVED** [review]
At what point do we pull the validation from GTFS-Lib and rely on this solely?!

**Comment by miles-grant-ibigroup** [comment]
> At what point do we pull the validation from GTFS-Lib and rely on this solely?!

There's still quite a few validators we'd have to get merged into the mobility data one. That will be a big project but probably one that would be appreciated by the community

**Comment by clinephi** [comment]
The community would definitely appreciate it! :)

**Review by binh-dam-ibigroup — APPROVED** [review]
Works!

**Pull request merged**
