### PR TITLE
Normalize fields fix

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR supplements #371 by making `NormalizeFieldTransformation.substitutions` and `NormalizeFieldTransformation.capitalizationExceptions` not null if no default substitutions are specified in the configurations (at least an empty list is returned).

### CODE REVIEW

**Review by landonreed — APPROVED** [review]
Looks pretty good, only comment is that the test doesn't really verify that it successfully returns a list with two objects for the JSON_LIST arg. I don't really find the parameterized test cases that useful here -- it might be more effective to have two tests: one that checks null input is an empty list, and one that checks that it parses JSON_LIST as Substitutions.

**Comment by binh-dam-ibigroup** [comment]
> Looks pretty good, only comment is that the test doesn't really verify that it successfully returns a list with two objects for the JSON_LIST arg. I don't really find the parameterized test cases that useful here -- it might be more effective to have two tests: one that checks null input is an empty list, and one that checks that it parses JSON_LIST as Substitutions.

Right. Updated in https://github.com/ibi-group/datatools-server/pull/386/commits/06d46fe1bfb894d5faabf0fe6a8f3011f2233257.

**Review by landonreed — APPROVED** [review]
Perfect!

**Review by br648 — APPROVED** [review]
LGTM

**Pull request merged**
